#!/bin/bash 
#PBS -l nodes=nano1:ppn=1:gpus=1,walltime=96:00:00
#PBS -N CNQ_model
#PBS -o log_CNQ_model.txt
#PBS -e err_CNQ_model.txt 

# cd $PBS_O_WORKDIR
# source activate python2.7

python /content/mi_detection/CNQ_model_split_by_patient.py 1
python /content/mi_detection/CNQ_model_split_by_patient.py 2
python /content/mi_detection/CNQ_model_split_by_patient.py 3
python /content/mi_detection/CNQ_model_split_by_patient.py 4
python /content/mi_detection/CNQ_model_split_by_patient.py 5
python /content/mi_detection/CNQ_model_split_by_patient.py 6
python /content/mi_detection/CNQ_model_split_by_patient.py 7
python /content/mi_detection/CNQ_model_split_by_patient.py 8
python /content/mi_detection/CNQ_model_split_by_patient.py 9
python /content/mi_detection/CNQ_model_split_by_patient.py 10
python /content/mi_detection/CNQ_model_split_by_patient.py 11
python /content/mi_detection/CNQ_model_split_by_patient.py 12
python /content/mi_detection/CNQ_model_split_by_patient.py 13
python /content/mi_detection/CNQ_model_split_by_patient.py 14
python /content/mi_detection/CNQ_model_split_by_patient.py 15
python /content/mi_detection/CNQ_model_split_by_patient.py 16
python /content/mi_detection/CNQ_model_split_by_patient.py 17
python /content/mi_detection/CNQ_model_split_by_patient.py 18
python /content/mi_detection/CNQ_model_split_by_patient.py 19
python /content/mi_detection/CNQ_model_split_by_patient.py 20
python /content/mi_detection/CNQ_model_split_by_patient.py 21
python /content/mi_detection/CNQ_model_split_by_patient.py 22
python /content/mi_detection/CNQ_model_split_by_patient.py 23
python /content/mi_detection/CNQ_model_split_by_patient.py 24
python /content/mi_detection/CNQ_model_split_by_patient.py 25
python /content/mi_detection/CNQ_model_split_by_patient.py 26
python /content/mi_detection/CNQ_model_split_by_patient.py 27
python /content/mi_detection/CNQ_model_split_by_patient.py 28
python /content/mi_detection/CNQ_model_split_by_patient.py 29
python /content/mi_detection/CNQ_model_split_by_patient.py 30
python /content/mi_detection/CNQ_model_split_by_patient.py 31
python /content/mi_detection/CNQ_model_split_by_patient.py 32
python /content/mi_detection/CNQ_model_split_by_patient.py 33
python /content/mi_detection/CNQ_model_split_by_patient.py 34
python /content/mi_detection/CNQ_model_split_by_patient.py 35
python /content/mi_detection/CNQ_model_split_by_patient.py 36
python /content/mi_detection/CNQ_model_split_by_patient.py 37
python /content/mi_detection/CNQ_model_split_by_patient.py 38
python /content/mi_detection/CNQ_model_split_by_patient.py 39
python /content/mi_detection/CNQ_model_split_by_patient.py 40
python /content/mi_detection/CNQ_model_split_by_patient.py 41
python /content/mi_detection/CNQ_model_split_by_patient.py 42
python /content/mi_detection/CNQ_model_split_by_patient.py 43
python /content/mi_detection/CNQ_model_split_by_patient.py 44
python /content/mi_detection/CNQ_model_split_by_patient.py 45
python /content/mi_detection/CNQ_model_split_by_patient.py 46
python /content/mi_detection/CNQ_model_split_by_patient.py 47
python /content/mi_detection/CNQ_model_split_by_patient.py 48
python /content/mi_detection/CNQ_model_split_by_patient.py 49
python /content/mi_detection/CNQ_model_split_by_patient.py 50
